server:
  port: 8085
minio:
  endpoint: http://127.0.0.1:9000
  port: 9000
  accessKey:  anil
  secretKey:  anilsenocak
  secure: false
  bucket-name: commons # Bucket Name
  image-size: 10485760 #  Maximum size of picture file
  file-size: 1073741824 #  Maximum file size
